### ISSUE TITLE
Meaning of the distance threshold

### ISSUE THREAD

**Issue by pmorerio** [sc8668/RTMScore#10]
https://github.com/sc8668/RTMScore/blob/79475c4c1b68219a0845fdeaf7cfc73600513705/RTMScore/model/utils.py#L525

Hi, what is the meaning of the distance threshold in the loss? Does it implies that distances are modeled only in the 7 Angstrom range? 
Just as a curiosity, what happens if that threshold is increased?
https://github.com/sc8668/RTMScore/blob/79475c4c1b68219a0845fdeaf7cfc73600513705/scripts/train_model.py#L34

Thanks in advance for your time in answering.
Best,
P.

**Comment by sc8668** [comment]
It means that only the residue-atom pairs with their distances below 7 Angstrom are considered when constructing the MDN model.  
The model performance may be changed as the increase of the threshold. It is just a hyperparameter for the model, and  here we just use the value recommended in DeepDock,

**Comment by pmorerio** [comment]
Thank you very much for you time and consideration.
