### ISSUE TITLE
The AUC values presented in Table 6 and Figure 6A seem to be inconsistent.

### ISSUE THREAD

**Issue by zchwang** [sc8668/RTMScore#18]
The AUC value for RTMScore1 shown in Table 6 is 0.83, whereas in Figure 6A, the AUC appears to be below 0.8. These two results seem to be inconsistent. 
Did I overlook any details?

Best regards.

**Comment by sc8668** [comment]
Thanks for pointing out our negligence. The data in  Table 6 is right, while the AUC shown in Figure 6A may be confused with that of DEKOIS. The corrected figure is shown below.
![boxplot_auroc](https://github.com/sc8668/RTMScore/assets/91195970/82cd5eaf-9406-4db2-acd9-8e57d702ae79)

**Comment by zchwang** [comment]
Thank you for addressing my concerns.
