### ISSUE TITLE
Some of the ligands in CASF core set cannot be read by RDKit successfully

### ISSUE THREAD

**Issue by omotcha** [sc8668/RTMScore#6]
Hi Chao Shen, thanks for your work! I tried to evaluate RTMScore on CASF benchmark and it turned out that some of the ligands in CASF core set cannot be read by RDKit successfully thus the proceeding steps could not be done. If I added `sanitize=False` to `Chem.MolFromMol2Block` and `Chem.MolFromMolBlock` in RTMScore/RTMScore/data/data.py line 149 and 153, RDKit could read those ligands but I noticed that this would cause a slight difference to the final prediction. So I wonder if you ever encountered and how you handle this problem. Thanks.

**Comment by sc8668** [comment]
Some ligands in CASF benchmark have some mistakes, so in our study we re-converted all the ligands to SDF format with the convert.py script implemented in OpenEye software, and this could make almost all the ligands recognized by RDKit.

**Comment by omotcha** [comment]
Thanks!
