### ISSUE TITLE
Additive terms in MDN outputs

### ISSUE THREAD

**Issue by pmorerio** [sc8668/RTMScore#7]
https://github.com/sc8668/RTMScore/blob/79475c4c1b68219a0845fdeaf7cfc73600513705/RTMScore/model/model2.py#L531
Hello, thanks for sharing such great code!

What is the meaning of the `+1.1` and `+1` in the the output for `sigma` and `mu` in the mixture density network? Is it some kind of prior knowledge you incorporate in the model? Or simply some numeric regularization?

Thanks in advance for you answer.

P.

**Comment by sc8668** [comment]
The MDN module here is just inspired by DeepDock (https://github.com/OptiMaL-PSE-Lab/DeepDock). I guess they are just some numeric regularizations because **sigma** and **mu** represent the standard deviations and means of several Gaussians, respectively.

**Comment by pmorerio** [comment]
Thanks for the quick answer
