### ISSUE TITLE
Graph files on zenodo

### ISSUE THREAD

**Issue by pmorerio** [sc8668/RTMScore#9]
Hi, thank you again for sharing the code.
I am trying to use the `train_model.py` script along with the dataset downloaded from [https://zenodo.org/record/6623202#.Y0aQwtJBxH4](https://zenodo.org/record/6623202#.Y0aQwtJBxH4). The files required are not there, e.g. `v2020_train_p.bin`. Can you help on this? 

Thank you in advance,

Pietro

**Comment by sc8668** [comment]
You can find the file at https://zenodo.org/record/6859325#.Y0aU38hPoyg. It is because a updated version has been uploaded when revising the manuscript.

**Comment by pmorerio** [comment]
Thank you!
